workflows:
  ios-build:
    name: iOS Build (Verification)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "MohTeeFlair.xcworkspace"
        XCODE_SCHEME: "MohTeeFlair"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Verify iOS Build
        script: |
          # Building for simulator to verify code without needing Apple Developer signing
          xcodebuild \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Debug \
            -sdk iphonesimulator \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app

  android-release:
    name: Android Release
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
