workflows:
  ios-build: # Renamed to 'build' instead of 'release'
    name: iOS Build (Simulator/Debug)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "MohTeeFlair.xcworkspace"
        XCODE_SCHEME: "MohTeeFlair"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build iOS app (Debug)
        script: |
          # Building without signing for verification. 
          # Note: This will NOT produce an installable .ipa for real iPhones.
          xcode-project build-ipa \
            --workspace ios/$XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME \
            --mode debug \
            --sdk iphonesimulator
    artifacts:
      - build/ios/ipa/*.ipa

  android-release:
    name: Android Release
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
