workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_auth # Variable group for App Store Connect integration
      vars:
        XCODE_WORKSPACE: "MohTeeFlair.xcworkspace"
        XCODE_SCHEME: "MohTeeFlair"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch certificates and profiles from App Store Connect
          # We use the bundle ID directly. Profiles will be automatically created if 'create' is added.
          app-store-connect fetch-signing-files "com.mohteeflair" --type IOS_APP_STORE --install --create
          keychain add-certificates
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/$XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME \
            --mode release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mohteeflair@gmail.com
